language: php
script: 
    - phpunit

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm
    - 7.0

services: mysql

before_script:
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar install
